### ISSUE TITLE
[Meta] 已翻譯清單 & 章節認領區

### ISSUE THREAD

**Issue by askeing** [askeing/rust-book#16]
請開啟新的 issue，標題為想翻譯的章節，然後 reference 到這個 issue。
可參考這兩個例子：https://github.com/askeing/rust-book/issues/11 和 https://github.com/askeing/rust-book/issues/13

以下為尚未完成清單：
- [x] \* [簡介](../blob/master/src/README.md)
- [x] \* [準備](../blob/master/src/getting-started.md)
- [x] \* [教學: 猜數字遊戲](../blob/master/src/guessing-game.md)
- [x] \* [語法及語意](../blob/master/src/syntax-and-semantics.md)
- [x]     \* [變數綁定](../blob/master/src/variable-bindings.md)
- [x]     \* [函式](../blob/master/src/functions.md)
- [x]     \* [基本型別](../blob/master/src/primitive-types.md)
- [x]     \* [註解](../blob/master/src/comments.md)
- [x]     \* [if](../blob/master/src/if.md)
- [x]     \* [迴圈](../blob/master/src/loops.md)
- [x]     \* [所有權](../blob/master/src/ownership.md)
- [x]     \* [參照與借用](../blob/master/src/references-and-borrowing.md)
- [x]     \* [生命週期](../blob/master/src/lifetimes.md)
- [x]     \* [可變性](../blob/master/src/mutability.md)
- [x]     \* [結構體](../blob/master/src/structs.md)
- [x]     \* [枚舉](../blob/master/src/enums.md)
- [x]     \* [Match](../blob/master/src/match.md)
- [x]     \* [模式](../blob/master/src/patterns.md)
- [x]     \* [Method Syntax](../blob/master/src/method-syntax.md)
- [x]     \* [向量](../blob/master/src/vectors.md)
- [x]     \* [字串](../blob/master/src/strings.md)
- [x]     \* [泛型](../blob/master/src/generics.md)
- [x]     \* [Traits](../blob/master/src/traits.md)
- [ ]     \* [Drop](../blob/master/src/drop.md)
- [x]     \* [if let](../blob/master/src/if-let.md)
- [ ]     \* [Trait Objects](../blob/master/src/trait-objects.md)
- [ ]     \* [Closures](../blob/master/src/closures.md)
- [ ]     \* [Universal Function Call Syntax](../blob/master/src/ufcs.md)
- [ ]     \* [Crates and Modules](../blob/master/src/crates-and-modules.md)
- [ ]     \* [`const` and `static`](../blob/master/src/const-and-static.md)
- [ ]     \* [Attributes](../blob/master/src/attributes.md)
- [ ]     \* [`type` aliases](../blob/master/src/type-aliases.md)
- [ ]     \* [Casting between types](../blob/master/src/casting-between-types.md)
- [ ]     \* [Associated Types](../blob/master/src/associated-types.md)
- [ ]     \* [Unsized Types](../blob/master/src/unsized-types.md)
- [ ]     \* [Operators and Overloading](../blob/master/src/operators-and-overloading.md)
- [ ]     \* [Deref coercions](../blob/master/src/deref-coercions.md)
- [ ]     \* [Macros](../blob/master/src/macros.md)
- [ ]     \* [Raw Pointers](../blob/master/src/raw-pointers.md)
- [ ]     \* [`unsafe`](../blob/master/src/unsafe.md)
- [ ] \* [Effective Rust](../blob/master/src/effective-rust.md)
- [ ]     \* [The Stack and the Heap](../blob/master/src/the-stack-and-the-heap.md)
- [ ]     \* [Testing](../blob/master/src/testing.md)
- [ ]     \* [Conditional Compilation](../blob/master/src/conditional-compilation.md)
- [ ]     \* [Documentation](../blob/master/src/documentation.md)
- [ ]     \* [Iterators](../blob/master/src/iterators.md)
- [ ]     \* [Concurrency](../blob/master/src/concurrency.md)
- [ ]     \* [Error Handling](../blob/master/src/error-handling.md)
- [ ]     \* [Choosing your Guarantees](../blob/master/src/choosing-your-guarantees.md)
- [ ]     \* [FFI](../blob/master/src/ffi.md)
- [ ]     \* [Borrow and AsRef](../blob/master/src/borrow-and-asref.md)
- [ ]     \* [Release Channels](../blob/master/src/release-channels.md)
- [ ]     \* [Using Rust without the standard library](../blob/master/src/using-rust-without-the-standard-library.md)
- [ ] \* [Nightly Rust](../blob/master/src/nightly-rust.md)
- [ ]     \* [Compiler Plugins](../blob/master/src/compiler-plugins.md)
- [ ]     \* [Inline Assembly](../blob/master/src/inline-assembly.md)
- [ ]     \* [No stdlib](../blob/master/src/no-stdlib.md)
- [ ]     \* [Intrinsics](../blob/master/src/intrinsics.md)
- [ ]     \* [Lang items](../blob/master/src/lang-items.md)
- [ ]     \* [Advanced linking](../blob/master/src/advanced-linking.md)
- [ ]     \* [Benchmark Tests](../blob/master/src/benchmark-tests.md)
- [ ]     \* [Box Syntax and Patterns](../blob/master/src/box-syntax-and-patterns.md)
- [ ]     \* [Slice Patterns](../blob/master/src/slice-patterns.md)
- [ ]     \* [Associated Constants](../blob/master/src/associated-constants.md)
- [ ]     \* [Custom Allocators](../blob/master/src/custom-allocators.md)
- [x] \* [詞彙表](../blob/master/src/glossary.md)
- [ ] \* [語法索引](../blob/master/src/syntax-index.md)
- [x] \* [參考文獻](../blob/master/src/bibliography.md)

**Comment by 3442853561** [comment]
認領 const  and  static

**Comment by 3442853561** [comment]
認領Drop
